install.packages("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")
BiocManager::install("optparse")
install.packages(c("readr", "magrittr", "tidyr", "jsonlite"), repos="http://cran.us.r-project.org")
